name: Automatisk uppdatering

on:
  schedule:
    # 30 = Minut, 17 = Timme (UTC), * = Varje dag, * = Varje månad, * = Varje veckodag
    - cron: '30 17 * * *'

jobs:
  uppdatera:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kod
        uses: actions/checkout@v5

      - name: Installera Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Installera bibliotek
        run: |
          pip install -r requirements.txt

      - name: Kör skripten i ordning
        run: |
          python update_standings.py
          python app.py

      - name: Spara och skicka ändringar
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Automatisk uppdatering" || exit 0
          git push
